site_name: SQL & Java - Your getting started Guide
site_url: https://rainbowdashlabs.github.io/BasicSQLPlugin/
site_description: Your goto page when you start with java and sql.
repo_url: https://github.com/RainbowDashLabs/BasicSQLPlugin/
repo_name: Basic SQL Plugin
plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
nav:
  - Home: index.md
  - 'Chapter 1 Getting Started':
    - 'Preface': 01/preface.md
    - 'Introduction': 01/introduction.md
    - 'About Databases': 01/about_databases.md
    - 'Project Setup': 01/setup.md
  - 'Chapter 2 Basic Data Operations':
    - 'Introduction': 02/introduction.md
    - 'Operators': 02/operators.md
    - 'SQL Datatypes': 02/sql_datatypes.md
    - 'Datatypes':
      - 'SQLite': 02/datatypes/sqlite.md
      - 'MariaDB and MySQL': 02/datatypes/mariadb_mysql.md
      - 'PostgreSQL': 02/datatypes/postgresql.md
    - 'Naming Conventions': 02/naming.md
    - 'Code Style': 02/code_style.md
    - 'Database Creation': 02/database_creation.md
    - 'Tables': 02/tables.md
    - 'Insert': 02/insert.md
    - 'Select': 02/select.md
    - 'Update': 02/update.md
    - 'Delete': 02/delete.md
  - 'Chapter 3 Data Consistency and advanced operations':
      - 'Introduction': 03/introduction.md
      - 'Query Planer': 03/query_planer.md
      - 'Query Planer Details':
        - 'Postgres': 03/query_planer/postgres.md
        - 'MariaDB': 03/query_planer/mariadb.md
        - 'MySQL': 03/query_planer/mysql.md
        - 'SqLite': 03/query_planer/sqlite.md
      - 'Data Consistency': 03/data_consistency.md
      - 'Data Consistency Methods':
        - 'Null Values': 03/data_consistency/null_values.md
        - 'Default Values': 03/data_consistency/default_values.md
        - 'Unique Indice': 03/data_consistency/unique_indice.md
        - 'Primary Keys': 03/data_consistency/primary_keys.md
        - 'Auto Increment': 03/data_consistency/auto_increment.md
        - 'Foreign Keys': 03/data_consistency/foreign_keys.md
        - 'Checks': 03/data_consistency/checks.md
      - 'More about Indice': 03/more_indice.md
      - 'Even more about Indice':
        - 'Sorted Indice': 03/more_indice/sorted_indice.md
        - 'Conditional indice': 03/more_indice/conditional_indice.md
        - 'Indice and expressions': 03/more_indice/indice_and_expressions.md
      - 'Upsert and Conflict handling': 03/upsert.md
      - 'Aggregation': 03/aggregation.md
      - 'Normalization': 03/normalization.md
      - 'Joins': 03/joins.md
      - 'Views': 03/views.md

theme:
  features:
    - navigation.instant
    - navigation.tracking
#    - navigation.expand
#    - navigation.tabs
#    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - content.code.annotate
  language: en
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: light blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
